api/urls.py
from . import views
from django.urls import path 

urlpatterns = [
    path('get_userdata/',views.get_userdata.as_view()),
    path('no_id/',views.no_id.as_view()),
    path('update_data/',views.update_data.as_view()),
]

myWebApps/urls.py
from django.urls import path 
from . import views
from django.views.generic import TemplateView

app_name = 'myWeb'
urlpatterns = [
    path('',views.home, name='home'),
    path('authenUser/',views.authenUser, name='authenUser'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('changepass/',views.changepass,name='changepass'),
    path('passChanged/',views.passChanged,name='passChanged'),
    path('adminHome/',views.adminHome,name='adminHome'),
    path('userPage/id=<int:user_id>',views.userPage,name='userPage'),
    path('home_package/',views.adminHome_package,name='home_package'),
    path('package_action/<int:package_id>',views.package_action, name='package_action'),
    path('new_package/',views.new_package,name="new_package"),
    path('delete_log/<int:id>',views.delete_log,name="delete_log"),
    path('expense/<int:user_id>',views.expense, name="expense"),
    path('adminchangepass/<int:user_id>',views.adminchangepass,name='adminchangepass'),
    path('adminpassChanged/<int:user_id>',views.adminpassChanged,name='adminpassChanged'),
    path('adminlibrary/',views.adminlibrary,name='adminlibrary'),
    path('libraryuserPage/<int:user_id>',views.libraryuserPage, name='libraryuserPage'),
    path('libraryexpense/<int:user_id>',views.libraryexpense,name='libraryexpense'),
    path('adminstudentloan/',views.adminstudentloan,name='adminstudentloan'),
    path('studentloanuserPage/<int:user_id>',views.studentloanuserPage, name='studentloanuserPage'),
    path('searchuser/>',views.searchuser,name ='searchuser'),
    path('searchpoint/>',views.searchpoint,name ='searchpoint'),
]

server/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('myWebApps.urls')),

]

myWebApps/models.py
from django.db import models

# Create your models here.

myWebApps/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse ,HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password
from api.models import UserPoints, UserLog, Package

def home(request):
    if request.user.is_authenticated:
        if request.user.username == "adminlibrary":
            return HttpResponseRedirect(reverse('myWeb:adminlibrary'))
        elif request.user.username == "adminstudentloan":
            return HttpResponseRedirect(reverse('myWeb:adminstudentloan'))
        if request.user.is_superuser:
            return HttpResponseRedirect(reverse('myWeb:adminHome'))
        else:
            user = User.objects.get(username=request.user.username)
            try:
                thisUser = UserPoints.objects.get(user=user.id)
                userlog = UserLog.objects.filter(user=user.id)
                points = thisUser.points
                log = []
                for data in userlog:
                    if(data.package_id!="-"):
                        thisPackage = Package.objects.get(package_id=data.package_id)
                        temp_data = {"id":data.id,
                                    "datetime":data.datetime,
                                    "package_id":data.package_id,
                                    "name":thisPackage.name,
                                    "points":thisPackage.points,
                                    "InEx":data.InEx}
                        log.append(temp_data)
                    else:
                        temp_data = {"id":data.id,
                                    "datetime":data.datetime,
                                    "package_id":"-",
                                    "name":"-",
                                    "points":data.points,
                                    "InEx":data.InEx}
                        log.append(temp_data)
            except:
                return render(request, 'home.html',{'points':points, 'log':log})
            else:
                return render(request, 'home.html',{'points':points, 'log':log})
                # return HttpResponseRedirect(reverse('myWeb:login'))
    else:
        return HttpResponseRedirect(reverse('myWeb:login'))

def adminHome_package(request):
    if request.user.is_superuser:
        list_package = Package.objects.all()
        return render(request, 'adminHome.html',{'list_package':list_package,'package':True })
    else:
        return HttpResponseRedirect(reverse('myWeb:login'))

def adminHome(request):
    if request.user.is_superuser:
        list_user = User.objects.filter(is_superuser=False).exclude(username="adminlibrary").exclude(username="adminstudentloan")
        return render(request, 'adminHome.html',{'list_user':list_user,'package':False })
    else:
        return HttpResponseRedirect(reverse('myWeb:login'))


def login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('myWeb:home'))
    else:
        return render(request, 'login.html')
        
def authenUser(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        auth_login(request, user)
        return redirect('/')
    else:
        return render(request,'login.html',{'err': "Error, username or password is not correct"})

def logout(request):
    auth_logout(request)
    return render(request,'login.html',{'err': "Log Out Complete!"})

def changepass(request):
    if request.user.is_authenticated:
        return render(request,'changepass.html')
    else:
        return HttpResponseRedirect(reverse('myWeb:login'))

def passChanged(request):
    username = request.user.username
    user = User.objects.get(username=username)
    if check_password(request.POST['Opassword'], user.password):
        if(request.POST['Npassword']==request.POST['Cpassword']):
            user.set_password(request.POST['Npassword'])
            user.save()
            user = authenticate(request, username=username, password=request.POST['Npassword'])
            auth_login(request, user)
            return HttpResponseRedirect(reverse('myWeb:home'))
        else:
            return render(request,'changepass.html',{'err':"Confirmed password does not match."})
    else:
        return render(request,'changepass.html',{'err':"Old password incorrect."})

def userPage(request,user_id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            user = User.objects.get(id=user_id)
            thisUser = UserPoints.objects.get(user=user_id)
            userlog = UserLog.objects.filter(user=user_id)
            points = thisUser.points
            log = []
            for data in userlog:
                if(data.package_id!="-"):
                    thisPackage = Package.objects.get(package_id=data.package_id)
                    temp_data = {"id":data.id,
                                "datetime":data.datetime,
                                "package_id":data.package_id,
                                "name":thisPackage.name,
                                "points":thisPackage.points,
                                "InEx":data.InEx}
                    log.append(temp_data)
                else:
                    temp_data = {"id":data.id,
                                "datetime":data.datetime,
                                "package_id":"-",
                                "name":"-",
                                "points":data.points,
                                "InEx":data.InEx}
                    log.append(temp_data)
            return render(request,'userPage.html',{'points':points,'username':user.username, 'log':log,'user_id':user_id})
        else:
            return HttpResponseRedirect(reverse('myWeb:home'))
    else:
        return HttpResponseRedirect(reverse('myWeb:login'))

def package_action(request,package_id):
    if request.user.is_superuser:
        try:
            if(request.POST['save']):
                thisPackage = Package.objects.get(package_id=package_id)
                thisPackage.package_id = request.POST['package_id']
                thisPackage.name = request.POST['name']
                thisPackage.type = request.POST['type']
                thisPackage.points = request.POST['points']
                thisPackage.material = request.POST['material']
                thisPackage.save()
            else:
                Package.objects.get(package_id=package_id).delete()
        except:
            Package.objects.get(package_id=package_id).delete()
        return HttpResponseRedirect(reverse('myWeb:home_package'))
    else:
        return HttpResponseRedirect(reverse('myWeb:login'))

def new_package(request):
    if request.user.is_superuser:

            try:
                Package.objects.create(package_id=request.POST['package_id'],
                                        name=request.POST['name'],
                                        type=request.POST['type'],
                                        material=request.POST['material'],
                                        points=request.POST['points'])
            except:
                return render(request,'adminHome.html',{'err':"Please Fill All Data."})
            else:
                return HttpResponseRedirect(reverse('myWeb:home_package'))
    else:
        return HttpResponseRedirect(reverse('myWeb:login'))

def delete_log(request,id):
    if request.user.is_superuser:
        username = UserLog.objects.get(id=id).user
        thisUser = User.objects.get(username=username)
        thisUserPoint = UserPoints.objects.get(user=thisUser.id)
        if(UserLog.objects.get(id=id).InEx == "Income"):
            delete_points = Package.objects.get(package_id=UserLog.objects.get(id=id).package_id).points
            thisUserPoint.points = thisUserPoint.points-delete_points
            thisUserPoint.save()
        else:
            delete_points = UserLog.objects.get(id=id).points
            thisUserPoint.points = thisUserPoint.points+delete_points
            thisUserPoint.save()
        UserLog.objects.get(id=id).delete()
        return HttpResponseRedirect(reverse('myWeb:userPage', args=(),
                                    kwargs={'user_id': thisUser.id}))

    else:
        return HttpResponseRedirect(reverse('myWeb:login'))

def expense(request,user_id):
    if request.user.is_superuser:
        thisUserPoints = UserPoints.objects.get(user=user_id)
        if(thisUserPoints.points>=int(request.POST["ex_points"])):
            thisUserPoints.points=thisUserPoints.points - int(request.POST['ex_points'])
            thisUserPoints.save()
            thisUser = User.objects.get(id=user_id)
            UserLog.objects.create(user=thisUser,InEx="Expense",points=int(request.POST["ex_points"]))
            return HttpResponseRedirect(reverse('myWeb:userPage', args=(),
                                                kwargs={'user_id': user_id}))
        else:
            user = User.objects.get(id=user_id)
            thisUser = UserPoints.objects.get(user=user_id)
            userlog = UserLog.objects.filter(user=user_id)
            points = thisUser.points
            log = []
            for data in userlog:
                if(data.package_id!="-"):
                    thisPackage = Package.objects.get(package_id=data.package_id)
                    temp_data = {"id":data.id,
                                "datetime":data.datetime,
                                "package_id":data.package_id,
                                "name":thisPackage.name,
                                "points":thisPackage.points,

myWebApps/templates/adminHome.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
	.ssp {font-family: 'Source Sans Pro', sans-serif}
	body {margin:0;}
	* {
	box-sizing: border-box;
	}

	fieldset {
  display: block;
  margin-left: 10px;
  margin-right: 2px;
  padding-top: 0.35em;
  padding-bottom: 0.625em;
  padding-left: 0.75em;
  padding-right: 0.75em;
  border: 2px groove (internal value);
  width:380px;
	font-size:18px;
	}
	.small {
	  width:300px;
	}
	.left {
	  float:left;
	  width:50%;
	}
	.right {
	  float:left;
	  width:50%;
	}
	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 16px 32px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
		margin-left: 10px;
	  margin-right: 2px;
	  -webkit-transition-duration: 0.4s; /* Safari */
	  transition-duration: 0.4s;
	  cursor: pointer;
	}
	.button1 {
	  background-color: white;
	  color: black;
	  border: 2px solid #000000;
		position: relative;
	}

	.button1:hover {
	  background-color: #000000;
	  color: white;
	}
	.rightmenu {
		font-family: 'Source Sans Pro', sans-serif; background-color: green;
	}
	.leftmenu {
		font-family: 'Source Sans Pro', sans-serif; background-color: grey;
	}
	ul {
	  list-style-type: none;
	  margin: 0;
	  padding: 0;
	  overflow: hidden;
	  background-color: black	;
	  position: fixed;
	  top: 0;
	  width: 100%;
	}

	li {
	  float: left;
	}

	li a {
	  display: block;
	  color: white;
	  text-align: center;
	  padding: 14px 16px;
	  text-decoration: none;
	}

	.rightmenu {
	  background-color: red;
	  font-family: 'Source Sans Pro', sans-serif
	}
	.fix{
		background: url(https://www.mx7.com/i/22e/GfDUpm.JPG?fbclid=IwAR2s66fi7kWsj7ERaNnveSpOiOaJqgvvSE1x_EUOSHHzRlBRTHLE_zKfpV0);
		background-size: cover;
		margin: 0;
		padding: 0;
		position: fixed;
		top: 0;
		width: 100%;
		height: 100vh;
		z-index: -6;	
		}
	.overlay1{
		position: absolute;
		background-color: rgba(0, 0, 0, 0.6);
		height: 100%;
		width: 100%;
		z-index: -5;
	}	
	</style>
</head>
	<body>
	<div class="fix"><div class="overlay1"></div></div>
	<ul>
		<li><img src="https://www.kmutnb.ac.th/getattachment/about/symbols/logo_kmutnb-(6).png.aspx?width=250&height=246" width="42" height="42"></li>
		<li><a class="ssp" style="color: white">ADMIN</a></li>
        <li style="float:right"><a class="rightmenu" href="{% url 'myWeb:logout' %}">Logout</a></li>
        <li style="float:right"><a href="{% url 'myWeb:home' %}" class="ssp" >{{ user.get_username }}</a></li>
		<li><a class ="leftmenu" href="{% url 'myWeb:home' %}">USER</a></li>
		<li><a class ="leftmenu" href="{% url 'myWeb:home_package' %}">PACKAGE</a></li>
	</ul>
	</br>
	</br>
		<fieldset class="small">
		 <legend><h3 class="ssp" style="color: white">Admin</h3></legend>
			<span class="ssp" style="color: white">{{user.username}}<br><br></span>
			<form action="{% url 'myWeb:changepass' %}" method="post">
			<span class="ssp" style="color: white">{% csrf_token %}</span>
				<input type="submit" value="Change Password">
			</form>
		</fieldset>
		{% if package %}
			<fieldset>
			<legend><h3 class="ssp" style="color: white">list of packages</h3></legend>
				<table border="1">
				<tr  class="ssp" style="color: white">
					<th>Package ID</th>
					<th>Name</th>
					<th>Type</th>
					<th>Material</th>
					<th>Points</th>
				</tr>
						{% for p in list_package %}
							<div style="overflow-x:auto;"></div>
							<tr>
								<form action="{% url 'myWeb:package_action' p.package_id %}" method="post">
								{% csrf_token %}
								<td><input type="text" name="package_id" placeholder={{p.package_id}} value={{p.package_id}}></td>
								<td><input type="text" name="name" placeholder={{p.name}} value={{p.name}}></td>
								<td>
									<select name="type">
										<option value={{p.type}}>{{p.type}}</option>
										<option value=Can>Can</option>
										<option value=Bottle>Bottle</option>
									</select>
								</td>
								<td>
									<select name="material">
										<option value={{p.material}}>{{p.material}}</option>
										<option value=Plastic>Plastic</option>
										<option value=Metel>Meltel</option>
									</select>
								</td>
								<td><input type="text" name="points" placeholder={{p.points}} value={{p.points}}></td>
								<td><input type="submit" name="save" value="Save"></td>
								<td><input type="submit" name="delete" value="Delete"></td>
								</form>
							</tr>

							</div>
						</form>
						{% endfor %}
								<form action="{% url 'myWeb:new_package' %}" method="post">
								{% csrf_token %}
								<tr>
								<td><input type="text" name="package_id" placeholder="package_id"></td>
								<td><input type="text" name="name" placeholder="name"></td>
								<td>
									<select name="type">
										<option value=Can>Can</option>
										<option value=Bottle>Bottle</option>
									</select>
								</td>
								<td>
									<select name="material">
										<option value=Plastic>Plastic</option>
										<option value=Metel>Metel</option>
									</select>
								</td>
								<td><input type="text" name="points" placeholder="points"></td>
								<td><input type="submit" value="New"></td>
								</tr>
								</form>
				</table>
			</fieldset>
			{{ err }}
			</br>
		{% else %}
			<fieldset>
			<legend><h3 class="ssp" style="color: white">list of users</h3></legend>
				<span class="ssp" style="color: white">{% for u in list_user  %}</span>
					<a href="{% url 'myWeb:userPage' u.id %}">{{u.username}}</a></br>
				{% endfor %}
			</fieldset>
		{% endif %}
	</body>
</html>

myWebApps/templates/e-Studentloan.html
<!DOCTYPE html>
<html>
    <head>
        <title>e-Studentloan</title>
        <link href="https://fonts.googleapis.com/css?family=Kanit&display=swap" rel="stylesheet">
        <style>
            body{
                margin: 0%;
                padding: 0%;
            }
            .kanit {font-family : 'Kanit', sans-serif;}
            fieldset {
                display: block;
                margin-left: 10px;
                margin-right: 2px;
                padding-top: 0.35em;
                padding-bottom: 0.625em;
                padding-left: 0.75em;
                padding-right: 0.75em;
                border: 2px groove (internal value);
                width:550px;
                font-size:18px;
                }
            ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
                overflow: hidden;
                background-color:none	;
                position: fixed;
                top: 0;
                width: 100%;
                }
                .center {
                    display: block;
                    margin-left: auto;
                    margin-right: auto;
                    width: 50%;
                  }
                .box{
                    position:absolute;
                    top: -100px;
                    left: 50%;
                    transform: translate(-50%,50%);
                    width: 1100px;
                    height: 200px;
                    border-radius: 4px;
                    display: flex;
                }


                .box .imgBx{
                    widows: 150px;
                    flex: 150;
                }

                .box .imgBx img{
                    position:absolute;
                    top:15%;
                    right: 20%;
                }

                .box .imgBx1{
                    widows: 150px;
                    flex: 150;
                }

                .box .imgBx1 img{
                    position:absolute;
                    top:0%;
                    left: 20%;
                }

                .rightmenu {
                    font-family: 'Source Sans Pro', sans-serif; background-color: green;
                 }
                .outbutton{
                    position:fixed;
                    top :0;
                    right: 0;
                    background-color:red	;
                    display: block;
                    color: white;
                    text-align: center;
                    padding: 14px 16px;
                    text-decoration: none;
                }
                .textred{
                    font-family : 'Kanit', sans-serif;
                    color: red;
                }
                .search{
                    display: block;
                    position:absolute;
                    top: 250px;
                    left: 25%;
                    width: 900px;
                    font-family : 'Kanit', sans-serif;
                }

                .table{
                    display: block;
                    margin-left: auto;
                    margin-right: auto;
                    width: 50%;
                    font-family : 'Kanit', sans-serif;
                }
                .content{
                    font-family : 'Kanit', sans-serif;
                    text-align: center;
                }
                .contianer1{
                    background-image:url(https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/A2KqU29/4k-students-in-a-classroom-raising-hands-together_btlakygm__F0000.png) ;
                    background-size: cover;
                    position: relative;
                    top: 0%;
                    height: 100vh;
                    z-index: -6;
                }
                .overlay1{
                    position: absolute;
                    background-color: rgba(255, 255, 255, 0.9);
                    height: 100%;
                    width: 100%;
                    z-index: -5;
                }
                .fix{
                    margin: 0;
                    padding: 0;
                    position: fixed;
                    top: 0;
                    width: 100%;	
                    }
                
              
        </style>
    </head>
    <body> 
        </div>
        <div class="fix">
            <div class="contianer1">
                <div class="overlay1"></div>
            </div>
        </div>

        

        <div style="position:absolute;width: 100%;top:0%;left:0%">
        <div class="box">
            <div class="imgBx1">
                <img src="https://www.egov.go.th/upload/eservice-thumbnail/img_f5a48f5648fc4b81477c8f2de0215739.png" width="115" height="165">
            </div>
            <div class="content">
                <p style="position:absolute;top: 10%;left: 27.75%;width: 500px;font-size:200%">กองทุนเงินให้กู้ยืมเพื่อการศึกษา</p><br> 
            </div>
            <div class="content">
                <p style="position:absolute;top: 40%;left: 36%;width: 300px;font-size:130%">มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ</p>    
            </div>
            <div class="imgBx">
                <img src="https://www.kmutnb.ac.th/getattachment/about/symbols/logo_kmutnb-(6).png.aspx?width=250&height=246" width="100" height="100">
            </div>
        </div>
        
        <a class="outbutton" href="{% url 'myWeb:logout' %}">Logout</a> 
          
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <form action="{% url 'myWeb:searchuser' %}" method="post">
        {% csrf_token %}
        <span class="search">
            ค้นหารหัสนักศึกษา: <input class="kanit" type="text" name="studentid" placeholder="ป้อนรหัสนักศึกษา">
            <input class="kanit" type="submit" name="search" value="ค้นหา"></a>   
        </span>    
        </form>
        
        <fieldset class="table">
        <legend><h3 style="color: #ff9900">รหัสนักศึกษาที่มาใช้บริการ</h3></legend>
        {% for u in list_all_user %}
            <a href="{% url 'myWeb:studentloanuserPage' u.id %}">{{u.username}}</a></br>
        {% endfor %}       
        </fieldset>
        </div>


    </body>
</html>

myWebApps/templates/userPage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<style>
		.ssp {font-family: 'Source Sans Pro', sans-serif}
		body {margin:0;}

		* {
		box-sizing: border-box;
		}

		fieldset {
	display: block;
	margin-left: 10px;
	margin-right: 2px;
	padding-top: 0.35em;
	padding-bottom: 0.625em;
	padding-left: 0.75em;
	padding-right: 0.75em;
	border: 2px groove (internal value);
	width:550px;
		font-size:18px;
		}
		.small {
		width:300px;
		}
		.left {
		float:left;
		width:50%;
		}
		.right {
		float:left;
		width:50%;
		}
		.button {
		background-color: #4CAF50; /* Green */
		border: none;
		color: white;
		padding: 16px 32px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
			margin-left: 10px;
		margin-right: 2px;
		-webkit-transition-duration: 0.4s; /* Safari */
		transition-duration: 0.4s;
		cursor: pointer;
		}
		.button1 {
		background-color: white;
		color: black;
		border: 2px solid #000000;
		position: relative;
		}

		.button1:hover {
		background-color: #000000;
		color: white;
		}
		/*.rightmenu {
		background-color: green;
		}*/
		ul {
		list-style-type: none;
		margin: 0;
		padding: 0;
		overflow: hidden;
		background-color: black	;
		position: fixed;
		top: 0;
		width: 100%;
		}

		li {
		float: left;
		}

		.fix{
		margin: 0;
		padding: 0;
		position: fixed;
		top: 0;
		width: 100%;	
		}

		li a {
		display: block;
		color: white;
		text-align: center;
		padding: 14px 16px;
		text-decoration: none;
		}

		.rightmenu {
			font-family: 'Source Sans Pro', sans-serif; background-color: red;
		}
		.contianer{
			background-image:url(https://www.mx7.com/i/22e/GfDUpm.JPG?fbclid=IwAR2s66fi7kWsj7ERaNnveSpOiOaJqgvvSE1x_EUOSHHzRlBRTHLE_zKfpV0) ;
			background-size: cover;
			position: relative;
			top: 0%;
			height: 100vh;
			z-index: -10;
		}
		.overlay{
			position: fixed;
			background-color: rgba(0, 0, 0, 0.6);
			height: 100%;
			width: 100%;
			z-index: -5;
		}
		</style>
	</head>
	<body>
	<div class="fix">
		<div class="contianer">
			<div class="overlay"></div>
		</div>
	</div>
	
	<div style="position:absolute;width: 100%;top:0%;left:0%">
	<ul>
		<li><img src="https://www.kmutnb.ac.th/getattachment/about/symbols/logo_kmutnb-(6).png.aspx?width=250&height=246" width="42" height="42"></li>
		<li><a class="ssp">DATA</a></li>
        <li style="float:right"><a class="rightmenu" href="{% url 'myWeb:logout' %}">Logout</a></li>
        <li style="float:right"><a class="ssp" href="{% url 'myWeb:home' %}">{{ user.get_username }}</a></li>
	</ul>
	</br>
	</br>
		<fieldset class="small">
		 <legend><h3 class="ssp" style="color: white" >User Informations</h3></legend>
		 <span class="ssp" style="color: white">
			Username: {{username}}<br><br>
			Point(s): {{points}} <br><br>
		 </span>
		 	<form action="{% url 'myWeb:adminchangepass' user_id %}" method="get"><!-- url 'myWeb:adminchangepass'ไปที่urlพร้อมกับค่าuser id  -->
			<span class="ssp" style="color: white">
			</span>
				<input type="submit" value="Change Password">
			</form>
		</fieldset>
		<fieldset>
		<legend><h3 class="ssp" style="color: white">History</h3></legend>
				<span class="ssp" style="color: white">{% if log %}</span>
					<table border="1">
					<tr class="ssp" style="color: white">
						<th>datetime</th>
						<th>package_id</th>
						<th>package_name</th>
						<th>points</th>
						<th>In/Ex</th>
					</tr>
							<span class="ssp" style="color: white">{% for userLog in log %}</span>
							<div style="overflow-x:auto;"></div>
							<tr class="ssp" style="color: white">
								<form action="{% url 'myWeb:delete_log' userLog.id %}" method="post">
								{% csrf_token %}
								<td style="font-size: 80%">{{userLog.datetime}}</td>
								<td style="font-size: 80%">{{userLog.package_id}}</td>
								<td style="font-size: 80%">{{userLog.name}}</td>
								<td style="font-size: 80%">{{userLog.points}}</td>
								<td style="font-size: 80%">{{userLog.InEx}}</td>
								<td><input type="submit" name="delete" value="Delete"></td>
								</form>
							</tr>
							</div>
							<span>{% endfor%}</span>
					</table></br></br></br>
					<span class="ssp" style="color: white">{{err}}</span>
					<form action="{% url 'myWeb:expense' user_id %}" method="post">
					<span class="ssp" style="color: white">{% csrf_token %}</span>
					<input type="text" name="ex_points" placeholder="Expense Points">
					<input type="submit" value="Expense">
					</form>
				<span class="ssp" style="color: white">
					{% else %}
						There is No History of this Account.
					{% endif %}
				</span>
		</fieldset>
	</div>
	</body>
</html>